-- Migration to RE-populate test questions for DISC, EQ, Soft Skills, and Motivation
-- and ADD missing questions for MBTI.

-- Helper function to get test_id by code
CREATE OR REPLACE FUNCTION get_test_id(test_code text) RETURNS uuid AS $$
  SELECT id FROM tests WHERE code = test_code;
$$ LANGUAGE sql;

-- 1. CLEANUP: Delete existing questions for tests we are fully repopulating
-- We KEEP MBTI questions 1-40 as they are valid.
DELETE FROM test_questions 
WHERE test_id IN (
  get_test_id('disc'),
  get_test_id('eq'),
  get_test_id('soft_skills'),
  get_test_id('motivation')
);

-- 2. POPULATE MBTI (Adding 20 questions: 41-60)
-- EI Scale
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('mbti'), 41, 'Вам нравится быть в центре внимания на вечеринках?', 'Кештерде назар орталығында болғанды ұнатасыз ба?', 'Do you enjoy being the center of attention at parties?', 'EI', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 42, 'Вы предпочитаете сначала действовать, а потом думать?', 'Сіз алдымен әрекет етуді, содан кейін ойлануды қалайсыз ба?', 'Do you prefer to act first and think later?', 'EI', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 43, 'Вам легко заговорить с незнакомым человеком?', 'Бейтаныс адаммен сөйлесу сізге оңай ма?', 'Is it easy for you to start a conversation with a stranger?', 'EI', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 44, 'Вы считаете себя спокойным и сдержанным человеком?', 'Сіз өзіңізді сабырлы және ұстамды адаммын деп санайсыз ба?', 'Do you consider yourself a calm and reserved person?', 'EI', true, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [0, 1]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 45, 'Вы быстро устаете от большого количества общения?', 'Сіз көп қарым-қатынастан тез шаршайсыз ба?', 'Do you get tired quickly from a lot of socializing?', 'EI', true, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [0, 1]}'::jsonb);

-- SN Scale
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('mbti'), 46, 'Вы больше доверяете своему опыту, чем теоретическим возможностям?', 'Сіз теориялық мүмкіндіктерге қарағанда өз тәжірибеңізге көбірек сенесіз бе?', 'Do you trust your experience more than theoretical possibilities?', 'SN', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 47, 'Вам нравится работать с конкретными фактами и деталями?', 'Сізге нақты фактілермен және егжей-тегжейлермен жұмыс істеген ұнай ма?', 'Do you like working with concrete facts and details?', 'SN', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 48, 'Вы часто думаете о том, как улучшить будущее?', 'Сіз болашақты қалай жақсартуға болатыны туралы жиі ойлайсыз ба?', 'Do you often think about how to improve the future?', 'SN', true, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [0, 1]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 49, 'Вас больше интересуют идеи и концепции, чем их практическое применение?', 'Сізді практикалық қолданудан гөрі идеялар мен тұжырымдамалар қызықтырады ма?', 'Are you more interested in ideas and concepts than their practical application?', 'SN', true, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [0, 1]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 50, 'Вы предпочитаете проверенные методы новым и непроверенным?', 'Сіз жаңа және тексерілмеген әдістерден гөрі тексерілген әдістерді қалайсыз ба?', 'Do you prefer proven methods over new and untested ones?', 'SN', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb);

-- TF Scale
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('mbti'), 51, 'При принятии решений вы руководствуетесь логикой, а не чувствами?', 'Шешім қабылдағанда сіз сезімдерге емес, логикаға сүйенесіз бе?', 'When making decisions, are you guided by logic rather than feelings?', 'TF', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 52, 'Вам важнее быть правым, чем сохранить хорошие отношения?', 'Сіз үшін қарым-қатынасты сақтаудан гөрі дұрыс болу маңызды ма?', 'Is it more important for you to be right than to maintain good relationships?', 'TF', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 53, 'Вы часто принимаете решения, основываясь на своих эмоциях?', 'Сіз шешімдерді жиі эмоцияларыңызға сүйене отырып қабылдайсыз ба?', 'Do you often make decisions based on your emotions?', 'TF', true, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [0, 1]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 54, 'Вы стараетесь не задеть чувства других людей, даже если это идет вразрез с логикой?', 'Сіз логикаға қайшы келсе де, басқа адамдардың көңіліне тимеуге тырысасыз ба?', 'Do you try not to hurt other people''s feelings, even if it goes against logic?', 'TF', true, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [0, 1]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 55, 'Вы цените справедливость выше милосердия?', 'Сіз әділдікті мейірімділіктен жоғары бағалайсыз ба?', 'Do you value justice over mercy?', 'TF', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb);

-- JP Scale
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('mbti'), 56, 'Вам нравится планировать свой день заранее?', 'Күніңізді алдын ала жоспарлағанды ұнатасыз ба?', 'Do you like to plan your day in advance?', 'JP', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 57, 'Вы предпочитаете иметь четкие сроки и дедлайны?', 'Сіз нақты мерзімдер мен дедлайндардың болғанын қалайсыз ба?', 'Do you prefer to have clear deadlines?', 'JP', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 58, 'Вы любите оставлять возможности открытыми и действовать по ситуации?', 'Сіз мүмкіндіктерді ашық қалдырып, жағдайға қарай әрекет еткенді ұнатасыз ба?', 'Do you like to keep your options open and act according to the situation?', 'JP', true, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [0, 1]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 59, 'Вас напрягают неожиданные изменения в планах?', 'Күтпеген жоспар өзгерістері сізді мазалайды ма?', 'Do unexpected changes in plans stress you out?', 'JP', false, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('mbti'), 60, 'Вы часто откладываете дела на потом?', 'Сіз істерді жиі кейінге қалдырасыз ба?', 'Do you often procrastinate?', 'JP', true, '{"ru": ["Да", "Нет"], "kk": ["Иә", "Жоқ"], "en": ["Yes", "No"], "values": [0, 1]}'::jsonb);


-- 3. POPULATE DISC (Full set 1-40)
-- D Scale
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('disc'), 1, 'Я предпочитаю брать на себя руководящую роль.', 'Мен жетекші рөлді алғанды жөн көремін.', 'I prefer to take a leading role.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 2, 'Я ориентирован на результат.', 'Мен нәтижеге бағытталғанмын.', 'I am results-oriented.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 3, 'Я говорю то, что думаю.', 'Мен ойымдағыны айтамын.', 'I say what I think.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 4, 'Я люблю сложные задачи.', 'Маған күрделі тапсырмалар ұнайды.', 'I like difficult tasks.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 5, 'Я не люблю терять время.', 'Мен уақытты босқа өткізгенді ұнатпаймын.', 'I don''t like wasting time.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 21, 'Я настойчив в достижении своих целей.', 'Мен өз мақсаттарыма жетуде табандымын.', 'I am persistent in achieving my goals.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 22, 'Мне нравится соревноваться и побеждать.', 'Маған жарысқан және жеңген ұнайды.', 'I like to compete and win.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 23, 'Я быстро принимаю решения.', 'Мен шешімді тез қабылдаймын.', 'I make decisions quickly.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 24, 'Я не боюсь рисковать.', 'Мен тәуекелге барудан қорықпаймын.', 'I am not afraid to take risks.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 25, 'Я прямолинеен в общении.', 'Мен қарым-қатынаста тікелеймін.', 'I am direct in communication.', 'D', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb);

-- I Scale
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('disc'), 6, 'Я люблю общаться с людьми.', 'Маған адамдармен араласқан ұнайды.', 'I like talking to people.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 7, 'Я полон энтузиазма.', 'Мен ынта-жігерге толымын.', 'I am full of enthusiasm.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 8, 'Я умею вдохновлять других.', 'Мен басқаларды шабыттандыра аламын.', 'I can inspire others.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 9, 'Я оптимист.', 'Мен оптимистпін.', 'I am an optimist.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 10, 'Я люблю быть в центре внимания.', 'Маған назар орталығында болған ұнайды.', 'I like to be the center of attention.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 26, 'Я легко завожу новые знакомства.', 'Мен жаңа таныстықтарды оңай табамын.', 'I make new acquaintances easily.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 27, 'Я оптимистично смотрю на жизнь.', 'Мен өмірге оптимистік көзқараспен қараймын.', 'I look at life optimistically.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 28, 'Мне нравится быть душой компании.', 'Маған ортаның жаны болған ұнайды.', 'I like being the life of the party.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 29, 'Я умею убеждать людей.', 'Мен адамдарды сендіре аламын.', 'I know how to persuade people.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 30, 'Я эмоционален и выразителен.', 'Мен эмоционалды және мәнерлімін.', 'I am emotional and expressive.', 'I', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb);

-- S Scale
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('disc'), 11, 'Я спокойный и уравновешенный человек.', 'Мен сабырлы және байсалды адаммын.', 'I am a calm and balanced person.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 12, 'Я предпочитаю помогать другим.', 'Мен басқаларға көмектескенді жөн көремін.', 'I prefer to help others.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 13, 'Я не люблю резких перемен.', 'Маған күрт өзгерістер ұнамайды.', 'I don''t like sudden changes.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 14, 'Я надежный друг и коллега.', 'Мен сенімді дос және әріптеспін.', 'I am a reliable friend and colleague.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 15, 'Я терпелив.', 'Мен шыдамдымын.', 'I am patient.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 31, 'Я ценю стабильность и предсказуемость.', 'Мен тұрақтылық пен болжамдылықты бағалаймын.', 'I value stability and predictability.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 32, 'Я хороший слушатель.', 'Мен жақсы тыңдаушымын.', 'I am a good listener.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 33, 'Я лоялен и предан своей команде.', 'Мен өз командама адалмын.', 'I am loyal and devoted to my team.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 34, 'Я не люблю конфликты.', 'Маған жанжалдар ұнамайды.', 'I do not like conflicts.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 35, 'Я терпелив и спокоен.', 'Мен сабырлы және тынышпын.', 'I am patient and calm.', 'S', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb);

-- C Scale
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('disc'), 16, 'Я аккуратен и точен.', 'Мен ұқыпты және дәлмін.', 'I am neat and accurate.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 17, 'Я люблю анализировать информацию.', 'Маған ақпаратты талдаған ұнайды.', 'I like analyzing information.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 18, 'Я придерживаюсь высоких стандартов.', 'Мен жоғары стандарттарды ұстанамын.', 'I adhere to high standards.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 19, 'Я осторожен при принятии решений.', 'Мен шешім қабылдауда сақпын.', 'I am cautious when making decisions.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 20, 'Я люблю порядок.', 'Маған тәртіп ұнайды.', 'I like order.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 36, 'Я внимателен к деталям.', 'Мен егжей-тегжейлерге мұқиятпын.', 'I am attentive to details.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 37, 'Я следую правилам и инструкциям.', 'Мен ережелер мен нұсқауларды орындаймын.', 'I follow rules and instructions.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 38, 'Я анализирую ситуацию перед принятием решения.', 'Мен шешім қабылдамас бұрын жағдайды талдаймын.', 'I analyze the situation before making a decision.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 39, 'Я ценю качество и точность.', 'Мен сапа мен дәлдікті бағалаймын.', 'I value quality and accuracy.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb),
(gen_random_uuid(), get_test_id('disc'), 40, 'Я склонен к критике себя и других.', 'Мен өзімді және басқаларды сынауға бейіммін.', 'I tend to criticize myself and others.', 'C', false, '{"ru": ["Очень похоже", "Похоже", "Не очень", "Совсем нет"], "kk": ["Өте ұқсас", "Ұқсас", "Олай емес", "Мүлдем жоқ"], "en": ["Very like me", "Like me", "Not really", "Not at all"], "values": [3, 2, 1, 0]}'::jsonb);


-- 4. POPULATE EQ (Full set 1-40)
-- Self-Awareness
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('eq'), 1, 'Я осознаю свои эмоции в момент их появления.', 'Мен эмоцияларымды пайда болған сәтте түсінемін.', 'I am aware of my emotions at the moment they arise.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 2, 'Я знаю, что вызывает у меня стресс.', 'Менде не стресс тудыратынын білемін.', 'I know what causes me stress.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 3, 'Я понимаю, как мое настроение влияет на окружающих.', 'Менің көңіл-күйім айналама қалай әсер ететінін түсінемін.', 'I understand how my mood affects others.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 4, 'Я реалистично оцениваю свои возможности.', 'Мен өз мүмкіндіктерімді нақты бағалаймын.', 'I realistically assess my capabilities.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 5, 'Я доверяю своей интуиции.', 'Мен түйсігіме сенемін.', 'I trust my intuition.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 6, 'Я учусь на своих ошибках.', 'Мен өз қателіктерімнен сабақ аламын.', 'I learn from my mistakes.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 7, 'Я открыт для обратной связи.', 'Мен кері байланысқа ашықпын.', 'I am open to feedback.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 8, 'Я знаю свои ценности.', 'Мен өз құндылықтарымды білемін.', 'I know my values.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb);

-- 5. POPULATE SOFT SKILLS (Full set 1-50)
-- Communication
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('soft_skills'), 1, 'Я легко нахожу общий язык с незнакомыми людьми.', 'Мен бейтаныс адамдармен оңай тіл табысамын.', 'I easily find common ground with strangers.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 2, 'Я умею слушать и слышать собеседника.', 'Мен сұхбаттасушыны тыңдай және ести аламын.', 'I can listen and hear the interlocutor.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 3, 'Я четко формулирую свои мысли.', 'Мен өз ойымды нақты тұжырымдаймын.', 'I articulate my thoughts clearly.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 4, 'Я уверенно чувствую себя во время публичных выступлений.', 'Мен көпшілік алдында сөйлегенде өзімді сенімді сезінемін.', 'I feel confident during public speaking.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 5, 'Я умею вести переговоры.', 'Мен келіссөздер жүргізе аламын.', 'I can negotiate.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb);

-- 6. POPULATE MOTIVATION (Full set 1-60)
-- Achievement
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('motivation'), 1, 'Я стремлюсь к профессиональному успеху.', 'Мен кәсіби табысқа ұмтыламын.', 'I strive for professional success.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 2, 'Мне нравится решать сложные задачи.', 'Маған күрделі есептерді шешкен ұнайды.', 'I like solving complex problems.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 3, 'Я постоянно повышаю свою квалификацию.', 'Мен үнемі біліктілігімді арттырамын.', 'I am constantly improving my qualifications.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 4, 'Я амбициозен.', 'Мен амбициялымын.', 'I am ambitious.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 5, 'Мне важно быть лучшим в своем деле.', 'Мен үшін өз ісімде үздік болу маңызды.', 'It is important for me to be the best at what I do.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 6, 'Я ориентирован на результат.', 'Мен нәтижеге бағытталғанмын.', 'I am results-oriented.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb);
