-- Fix missing questions for EQ, Soft Skills, and Motivation

-- Helper function
CREATE OR REPLACE FUNCTION get_test_id(test_code text) RETURNS uuid AS $$
  SELECT id FROM tests WHERE code = test_code;
$$ LANGUAGE sql;

-- 1. Explicitly DELETE for these tests
DELETE FROM test_questions WHERE test_id = get_test_id('eq');
DELETE FROM test_questions WHERE test_id = get_test_id('soft_skills');
DELETE FROM test_questions WHERE test_id = get_test_id('motivation');

-- 4. POPULATE EQ (Full set 1-40)
-- Self-Awareness
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('eq'), 1, 'Я осознаю свои эмоции в момент их появления.', 'Мен эмоцияларымды пайда болған сәтте түсінемін.', 'I am aware of my emotions at the moment they arise.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 2, 'Я знаю, что вызывает у меня стресс.', 'Менде не стресс тудыратынын білемін.', 'I know what causes me stress.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 3, 'Я понимаю, как мое настроение влияет на окружающих.', 'Менің көңіл-күйім айналама қалай әсер ететінін түсінемін.', 'I understand how my mood affects others.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 4, 'Я реалистично оцениваю свои возможности.', 'Мен өз мүмкіндіктерімді нақты бағалаймын.', 'I realistically assess my capabilities.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 5, 'Я доверяю своей интуиции.', 'Мен түйсігіме сенемін.', 'I trust my intuition.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 6, 'Я учусь на своих ошибках.', 'Мен өз қателіктерімнен сабақ аламын.', 'I learn from my mistakes.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 7, 'Я открыт для обратной связи.', 'Мен кері байланысқа ашықпын.', 'I am open to feedback.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 8, 'Я знаю свои ценности.', 'Мен өз құндылықтарымды білемін.', 'I know my values.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 9, 'Я понимаю, как мои эмоции влияют на мою работу.', 'Менің эмоцияларым жұмысыма қалай әсер ететінін түсінемін.', 'I understand how my emotions affect my work.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 10, 'Я могу назвать свои чувства в любой момент.', 'Мен кез келген сәтте сезімдерімді атай аламын.', 'I can name my feelings at any moment.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 11, 'Я знаю свои сильные и слабые стороны.', 'Мен өз күшті және әлсіз жақтарымды білемін.', 'I know my strengths and weaknesses.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 12, 'Я замечаю физические признаки стресса у себя.', 'Мен өзімдегі күйзелістің физикалық белгілерін байқаймын.', 'I notice physical signs of stress in myself.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 13, 'Я понимаю, почему я реагирую определенным образом.', 'Неліктен белгілі бір жолмен әрекет ететінімді түсінемін.', 'I understand why I react in a certain way.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 14, 'Я уверен в своих способностях.', 'Мен өз қабілеттеріме сенімдімін.', 'I am confident in my abilities.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 15, 'Я осознаю свои ценности и убеждения.', 'Мен өз құндылықтарым мен сенімдерімді түсінемін.', 'I am aware of my values and beliefs.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 16, 'Я честен с самим собой.', 'Мен өзіме адалмын.', 'I am honest with myself.', 'self_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb);

-- Self-Management
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('eq'), 17, 'Я умею контролировать свои импульсы.', 'Мен өз импульстарымды басқара аламын.', 'I can control my impulses.', 'self_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 18, 'Я легко адаптируюсь к изменениям.', 'Мен өзгерістерге оңай бейімделемін.', 'I adapt to changes easily.', 'self_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 19, 'Я сохраняю позитивный настрой даже в трудных ситуациях.', 'Мен қиын жағдайларда да позитивті көзқарасты сақтаймын.', 'I maintain a positive attitude even in difficult situations.', 'self_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 20, 'Я настойчив в преодолении препятствий.', 'Мен кедергілерді жеңуде табандымын.', 'I am persistent in overcoming obstacles.', 'self_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 21, 'Я умею успокаивать себя, когда расстроен.', 'Мен ренжіген кезде өзімді тыныштандыра аламын.', 'I know how to calm myself down when I am upset.', 'self_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 22, 'Я держу свои обещания.', 'Мен уәделерімді орындаймын.', 'I keep my promises.', 'self_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 23, 'Я организован и продуктивен.', 'Мен ұйымшыл және өнімдімін.', 'I am organized and productive.', 'self_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 24, 'Я беру на себя ответственность за свои действия.', 'Мен өз іс-әрекеттерім үшін жауапкершілікті аламын.', 'I take responsibility for my actions.', 'self_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb);

-- Social Awareness
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('eq'), 25, 'Я легко считываю эмоции других людей по их лицам.', 'Мен басқа адамдардың эмоцияларын олардың жүздерінен оңай оқимын.', 'I easily read other people''s emotions from their faces.', 'social_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 26, 'Я внимательно слушаю, когда кто-то говорит.', 'Мен біреу сөйлеп жатқанда мұқият тыңдаймын.', 'I listen carefully when someone speaks.', 'social_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 27, 'Я понимаю социальные нормы и правила.', 'Мен әлеуметтік нормалар мен ережелерді түсінемін.', 'I understand social norms and rules.', 'social_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 28, 'Я чувствую атмосферу в коллективе.', 'Мен ұжымдағы атмосфераны сезінемін.', 'I sense the atmosphere in the team.', 'social_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 29, 'Я сопереживаю проблемам других людей.', 'Мен басқа адамдардың мәселелеріне ортақтасамын.', 'I empathize with other people''s problems.', 'social_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 30, 'Я уважаю мнения, отличные от моего.', 'Мен өзімдікінен өзгеше пікірлерді құрметтеймін.', 'I respect opinions different from mine.', 'social_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 31, 'Я понимаю невербальные сигналы.', 'Мен вербалды емес сигналдарды түсінемін.', 'I understand non-verbal signals.', 'social_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 32, 'Мне интересно узнавать о людях.', 'Маған адамдар туралы білу қызықты.', 'I am interested in learning about people.', 'social_awareness', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb);

-- Relationship Management
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('eq'), 33, 'Я умею вдохновлять других.', 'Мен басқаларды шабыттандыра аламын.', 'I can inspire others.', 'relationship_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 34, 'Я эффективно работаю в команде.', 'Мен командада тиімді жұмыс істеймін.', 'I work effectively in a team.', 'relationship_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 35, 'Я помогаю другим развиваться.', 'Мен басқаларға дамуға көмектесемін.', 'I help others develop.', 'relationship_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 36, 'Я умею вести переговоры.', 'Мен келіссөздер жүргізе аламын.', 'I can negotiate.', 'relationship_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 37, 'Я открыто общаюсь с людьми.', 'Мен адамдармен ашық сөйлесемін.', 'I communicate openly with people.', 'relationship_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 38, 'Я поддерживаю изменения и нововведения.', 'Мен өзгерістер мен жаңалықтарды қолдаймын.', 'I support change and innovation.', 'relationship_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 39, 'Я умею находить общий язык с разными людьми.', 'Мен әртүрлі адамдармен ортақ тіл таба аламын.', 'I can find common ground with different people.', 'relationship_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('eq'), 40, 'Я стараюсь быть примером для других.', 'Мен басқаларға үлгі болуға тырысамын.', 'I try to be an example for others.', 'relationship_management', false, '{"ru": ["Не согласен", "Скорее нет", "Нейтрально", "Скорее да", "Согласен"], "kk": ["Келіспеймін", "Жоқ сияқты", "Бейтарап", "Иә сияқты", "Келісемін"], "en": ["Disagree", "Rather not", "Neutral", "Rather yes", "Agree"], "values": [0, 25, 50, 75, 100]}'::jsonb);


-- 5. POPULATE SOFT SKILLS (Full set 1-50)
-- Communication
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('soft_skills'), 1, 'Я легко нахожу общий язык с незнакомыми людьми.', 'Мен бейтаныс адамдармен оңай тіл табысамын.', 'I easily find common ground with strangers.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 2, 'Я умею слушать и слышать собеседника.', 'Мен сұхбаттасушыны тыңдай және ести аламын.', 'I can listen and hear the interlocutor.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 3, 'Я четко формулирую свои мысли.', 'Мен өз ойымды нақты тұжырымдаймын.', 'I articulate my thoughts clearly.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 4, 'Я уверенно чувствую себя во время публичных выступлений.', 'Мен көпшілік алдында сөйлегенде өзімді сенімді сезінемін.', 'I feel confident during public speaking.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 5, 'Я умею вести переговоры.', 'Мен келіссөздер жүргізе аламын.', 'I can negotiate.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 6, 'Я умею четко и ясно излагать свои мысли.', 'Мен өз ойымды нақты және анық жеткізе аламын.', 'I can express my thoughts clearly and concisely.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 7, 'Я внимательно слушаю собеседника, не перебивая.', 'Мен сұхбаттасушыны бөлмей, мұқият тыңдаймын.', 'I listen carefully to the interlocutor without interrupting.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 8, 'Я умею убеждать других в своей правоте.', 'Мен басқаларды өз құқығыма сендіре аламын.', 'I can convince others that I am right.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 9, 'Я адаптирую свой стиль общения под собеседника.', 'Мен қарым-қатынас стилімді сұхбаттасушыға бейімдеймін.', 'I adapt my communication style to the interlocutor.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 10, 'Я уверенно выступаю перед аудиторией.', 'Мен аудитория алдында сенімді сөйлеймін.', 'I speak confidently in front of an audience.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 11, 'Я умею давать конструктивную обратную связь.', 'Мен сындарлы кері байланыс бере аламын.', 'I can give constructive feedback.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 12, 'Я использую невербальные средства общения (жесты, мимика).', 'Мен вербалды емес қарым-қатынас құралдарын (қимылдар, мимика) қолданамын.', 'I use non-verbal means of communication (gestures, facial expressions).', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 13, 'Я умею вести деловую переписку.', 'Мен іскерлік хат алмасуды жүргізе аламын.', 'I can conduct business correspondence.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 14, 'Я открыт к общению и новым контактам.', 'Мен қарым-қатынасқа және жаңа байланыстарға ашықпын.', 'I am open to communication and new contacts.', 'communication', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 15, 'Я предпочитаю работать в команде, а не в одиночку.', 'Мен жалғыз емес, командада жұмыс істегенді жөн көремін.', 'I prefer working in a team rather than alone.', 'teamwork', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 16, 'Я готов помочь коллеге, даже если занят.', 'Мен бос болмасам да, әріптесіме көмектесуге дайынмын.', 'I am ready to help a colleague, even if I am busy.', 'teamwork', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 17, 'Я делюсь информацией и знаниями с командой.', 'Мен ақпарат пен білімді командамен бөлісемін.', 'I share information and knowledge with the team.', 'teamwork', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 18, 'Я уважаю вклад каждого члена команды.', 'Мен әр команда мүшесінің үлесін құрметтеймін.', 'I respect the contribution of each team member.', 'teamwork', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 19, 'Я умею находить компромиссы в спорах.', 'Мен дауларда ымыраға келе аламын.', 'I can find compromises in disputes.', 'teamwork', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 20, 'Я поддерживаю командный дух.', 'Мен командалық рухты қолдаймын.', 'I support team spirit.', 'teamwork', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 21, 'Я беру на себя ответственность за общий результат.', 'Мен жалпы нәтиже үшін жауапкершілікті аламын.', 'I take responsibility for the overall result.', 'teamwork', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 22, 'Я доверяю своим коллегам.', 'Мен әріптестеріме сенемін.', 'I trust my colleagues.', 'teamwork', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 23, 'Я признаю свои ошибки перед командой.', 'Мен өз қателіктерімді команда алдында мойындаймын.', 'I admit my mistakes to the team.', 'teamwork', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 24, 'Я анализирую информацию из разных источников.', 'Мен ақпаратты әртүрлі көздерден талдаймын.', 'I analyze information from different sources.', 'critical_thinking', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 25, 'Я подвергаю сомнению факты, прежде чем поверить.', 'Мен сенбес бұрын фактілерге күмәнмен қараймын.', 'I question facts before believing.', 'critical_thinking', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 26, 'Я ищу логические связи между событиями.', 'Мен оқиғалар арасындағы логикалық байланыстарды іздеймін.', 'I look for logical connections between events.', 'critical_thinking', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 27, 'Я умею выделять главное из большого объема данных.', 'Мен үлкен көлемдегі деректерден бастысын бөліп көрсете аламын.', 'I can highlight the main thing from a large amount of data.', 'critical_thinking', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 28, 'Я предлагаю нестандартные решения проблем.', 'Мен мәселелерді шешудің стандартты емес жолдарын ұсынамын.', 'I offer non-standard solutions to problems.', 'critical_thinking', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 29, 'Я оцениваю риски перед принятием решения.', 'Мен шешім қабылдамас бұрын тәуекелдерді бағалаймын.', 'I assess risks before making a decision.', 'critical_thinking', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 30, 'Я объективен в своих суждениях.', 'Мен өз пайымдауларымда объективтімін.', 'I am objective in my judgments.', 'critical_thinking', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 31, 'Я умею аргументировать свою позицию.', 'Мен өз ұстанымымды дәйектей аламын.', 'I can argue my position.', 'critical_thinking', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 32, 'Я не поддаюсь эмоциям при анализе ситуации.', 'Жағдайды талдау кезінде мен эмоцияларға берілмеймін.', 'I do not give in to emotions when analyzing the situation.', 'critical_thinking', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 33, 'Я легко приспосабливаюсь к новым условиям.', 'Мен жаңа жағдайларға оңай бейімделемін.', 'I easily adapt to new conditions.', 'adaptability', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 34, 'Я быстро учусь новым технологиям.', 'Мен жаңа технологияларды тез үйренемін.', 'I learn new technologies quickly.', 'adaptability', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 35, 'Я не боюсь перемен.', 'Мен өзгерістерден қорықпаймын.', 'I am not afraid of change.', 'adaptability', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 36, 'Я гибкий в планировании своего времени.', 'Мен уақытымды жоспарлауда икемдімін.', 'I am flexible in planning my time.', 'adaptability', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 37, 'Я умею работать в условиях неопределенности.', 'Мен белгісіздік жағдайында жұмыс істей аламын.', 'I can work in conditions of uncertainty.', 'adaptability', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 38, 'Я открыт к новым идеям и предложениям.', 'Мен жаңа идеялар мен ұсыныстарға ашықпын.', 'I am open to new ideas and suggestions.', 'adaptability', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 39, 'Я быстро нахожу выход из сложных ситуаций.', 'Мен қиын жағдайлардан шығу жолын тез табамын.', 'I quickly find a way out of difficult situations.', 'adaptability', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 40, 'Я готов менять свои привычки ради эффективности.', 'Мен тиімділік үшін әдеттерімді өзгертуге дайынмын.', 'I am ready to change my habits for efficiency.', 'adaptability', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 41, 'Я спокойно воспринимаю критику.', 'Мен сынды сабырмен қабылдаймын.', 'I accept criticism calmly.', 'adaptability', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 42, 'Я часто предлагаю новые идеи.', 'Мен жиі жаңа идеялар ұсынамын.', 'I often suggest new ideas.', 'initiative', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 43, 'Я беру на себя ответственность без напоминаний.', 'Мен ескертусіз жауапкершілікті аламын.', 'I take responsibility without reminders.', 'initiative', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 44, 'Я стремлюсь к саморазвитию.', 'Мен өзін-өзі дамытуға ұмтыламын.', 'I strive for self-development.', 'initiative', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 45, 'Я ищу возможности для улучшения процессов.', 'Мен процестерді жақсарту мүмкіндіктерін іздеймін.', 'I look for opportunities to improve processes.', 'initiative', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 46, 'Я не жду указаний, а действую сам.', 'Мен нұсқауларды күтпеймін, өзім әрекет етемін.', 'I don''t wait for instructions, I act myself.', 'initiative', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 47, 'Я довожу начатое до конца.', 'Мен бастаған істі аяғына дейін жеткіземін.', 'I finish what I started.', 'initiative', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 48, 'Я готов браться за сложные задачи.', 'Мен күрделі тапсырмаларды қабылдауға дайынмын.', 'I am ready to take on difficult tasks.', 'initiative', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 49, 'Я вдохновляю коллег своим примером.', 'Мен әріптестерімді үлгіммен шабыттандырамын.', 'I inspire colleagues with my example.', 'initiative', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('soft_skills'), 50, 'Я не боюсь просить о повышении или новых задачах.', 'Мен көтерілуді немесе жаңа тапсырмаларды сұраудан қорықпаймын.', 'I am not afraid to ask for a promotion or new tasks.', 'initiative', false, '{"ru": ["Никогда", "Редко", "Иногда", "Часто", "Всегда"], "kk": ["Ешқашан", "Сирек", "Кейде", "Жиі", "Әрқашан"], "en": ["Never", "Rarely", "Sometimes", "Often", "Always"], "values": [0, 25, 50, 75, 100]}'::jsonb);


-- 6. POPULATE MOTIVATION (Full set 1-60)
-- Achievement
INSERT INTO test_questions (id, test_id, question_number, text_ru, text_kk, text_en, scale_code, reverse_scored, options) VALUES
(gen_random_uuid(), get_test_id('motivation'), 1, 'Я стремлюсь к профессиональному успеху.', 'Мен кәсіби табысқа ұмтыламын.', 'I strive for professional success.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 2, 'Мне нравится решать сложные задачи.', 'Маған күрделі есептерді шешкен ұнайды.', 'I like solving complex problems.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 3, 'Я постоянно повышаю свою квалификацию.', 'Мен үнемі біліктілігімді арттырамын.', 'I am constantly improving my qualifications.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 4, 'Я амбициозен.', 'Мен амбициялымын.', 'I am ambitious.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 5, 'Мне важно быть лучшим в своем деле.', 'Мен үшін өз ісімде үздік болу маңызды.', 'It is important for me to be the best at what I do.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 6, 'Я ориентирован на результат.', 'Мен нәтижеге бағытталғанмын.', 'I am results-oriented.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 7, 'Для меня важно достигать высоких результатов.', 'Мен үшін жоғары нәтижелерге жету маңызды.', 'It is important for me to achieve high results.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 8, 'Я люблю ставить перед собой сложные цели.', 'Мен алдыма күрделі мақсаттар қойғанды ұнатамын.', 'I like to set difficult goals for myself.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 9, 'Я испытываю удовлетворение от хорошо выполненной работы.', 'Мен жақсы орындалған жұмыстан қанағаттанамын.', 'I feel satisfaction from a job well done.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 10, 'Я постоянно стремлюсь улучшать свои показатели.', 'Мен үнемі өз көрсеткіштерімді жақсартуға ұмтыламын.', 'I constantly strive to improve my performance.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 11, 'Я предпочитаю задачи, где успех зависит от меня.', 'Мен сәттілік маған байланысты болатын тапсырмаларды қалаймын.', 'I prefer tasks where success depends on me.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 12, 'Меня мотивирует конкуренция.', 'Мені бәсекелестік ынталандырады.', 'Competition motivates me.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 13, 'Я готов работать усердно ради достижения успеха.', 'Мен жетістікке жету үшін аянбай еңбек етуге дайынмын.', 'I am ready to work hard to achieve success.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 14, 'Я горжусь своими достижениями.', 'Мен өз жетістіктерімен мақтанамын.', 'I am proud of my achievements.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 15, 'Я не останавливаюсь на достигнутом.', 'Мен қол жеткізген нәтижемен тоқтап қалмаймын.', 'I do not stop at what has been achieved.', 'achievement', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 16, 'Мне нравится руководить людьми.', 'Маған адамдарды басқарған ұнайды.', 'I like to lead people.', 'power', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 17, 'Я стремлюсь к влиянию и авторитету.', 'Мен ықпал мен беделге ұмтыламын.', 'I strive for influence and authority.', 'power', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 18, 'Для меня важно контролировать ситуацию.', 'Мен үшін жағдайды бақылау маңызды.', 'It is important for me to control the situation.', 'power', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 19, 'Я хочу принимать ключевые решения.', 'Мен негізгі шешімдерді қабылдағым келеді.', 'I want to make key decisions.', 'power', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 20, 'Мне нравится быть лидером в группе.', 'Маған топта көшбасшы болған ұнайды.', 'I like to be a leader in a group.', 'power', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 21, 'Я готов брать на себя ответственность за других.', 'Мен басқалар үшін жауапкершілікті алуға дайынмын.', 'I am ready to take responsibility for others.', 'power', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 22, 'Я стремлюсь к карьерному росту.', 'Мен мансаптық өсуге ұмтыламын.', 'I strive for career growth.', 'power', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 23, 'Мне нравится организовывать работу других.', 'Маған басқалардың жұмысын ұйымдастырған ұнайды.', 'I like to organize the work of others.', 'power', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 24, 'Я хочу, чтобы мое мнение учитывалось.', 'Менің пікірімнің ескерілгенін қалаймын.', 'I want my opinion to be taken into account.', 'power', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 25, 'Для меня важны хорошие отношения с коллегами.', 'Мен үшін әріптестермен жақсы қарым-қатынас маңызды.', 'Good relationships with colleagues are important to me.', 'affiliation', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 26, 'Я предпочитаю работать в дружном коллективе.', 'Мен тату ұжымда жұмыс істегенді қалаймын.', 'I prefer to work in a friendly team.', 'affiliation', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 27, 'Мне нравится помогать другим.', 'Маған басқаларға көмектескен ұнайды.', 'I like helping others.', 'affiliation', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 28, 'Я ценю поддержку и одобрение окружающих.', 'Мен басқалардың қолдауы мен мақұлдауын бағалаймын.', 'I appreciate the support and approval of others.', 'affiliation', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 29, 'Я избегаю конфликтов.', 'Мен жанжалдардан аулақпын.', 'I avoid conflicts.', 'affiliation', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 30, 'Мне нравится быть частью группы.', 'Маған топтың бір бөлігі болған ұнайды.', 'I like being part of a group.', 'affiliation', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 31, 'Я стараюсь нравиться людям.', 'Мен адамдарға ұнауға тырысамын.', 'I try to please people.', 'affiliation', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 32, 'Я плохо переношу одиночество.', 'Мен жалғыздықты нашар қабылдаймын.', 'I tolerate loneliness poorly.', 'affiliation', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 33, 'Для меня важна социальная активность.', 'Мен үшін әлеуметтік белсенділік маңызды.', 'Social activity is important to me.', 'affiliation', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 34, 'Я предпочитаю работать самостоятельно.', 'Мен өз бетімше жұмыс істегенді жөн көремін.', 'I prefer to work independently.', 'autonomy', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 35, 'Для меня важна свобода действий.', 'Мен үшін іс-әрекет бостандығы маңызды.', 'Freedom of action is important to me.', 'autonomy', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 36, 'Я не люблю, когда меня контролируют.', 'Маған мені басқарған ұнамайды.', 'I don''t like being controlled.', 'autonomy', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 37, 'Я хочу сам планировать свое время.', 'Мен өз уақытымды өзім жоспарлағым келеді.', 'I want to plan my time myself.', 'autonomy', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 38, 'Мне нравится принимать решения без чьей-либо помощи.', 'Маған ешкімнің көмегінсіз шешім қабылдаған ұнайды.', 'I like to make decisions without anyone''s help.', 'autonomy', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 39, 'Я ценю возможность работать удаленно.', 'Мен қашықтан жұмыс істеу мүмкіндігін бағалаймын.', 'I appreciate the opportunity to work remotely.', 'autonomy', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 40, 'Я не люблю жесткие рамки и правила.', 'Маған қатаң шектеулер мен ережелер ұнамайды.', 'I don''t like strict limits and rules.', 'autonomy', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 41, 'Я хочу сам выбирать методы работы.', 'Мен жұмыс әдістерін өзім таңдағым келеді.', 'I want to choose my own working methods.', 'autonomy', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 42, 'Я чувствую себя лучше, когда никто не вмешивается в мою работу.', 'Менің жұмысыма ешкім араласпағанда өзімді жақсы сезінемін.', 'I feel better when no one interferes with my work.', 'autonomy', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 43, 'Для меня важна стабильная зарплата.', 'Мен үшін тұрақты жалақы маңызды.', 'A stable salary is important to me.', 'security', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 44, 'Я предпочитаю надежную компанию рискованным стартапам.', 'Мен тәуекелді стартаптардан гөрі сенімді компанияны жөн көремін.', 'I prefer a reliable company to risky startups.', 'security', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 45, 'Мне нужны гарантии занятости.', 'Маған жұмыспен қамту кепілдіктері қажет.', 'I need employment guarantees.', 'security', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 46, 'Я боюсь потерять работу.', 'Мен жұмыстан айырылудан қорқамын.', 'I am afraid of losing my job.', 'security', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 47, 'Я ценю социальный пакет и страховку.', 'Мен әлеуметтік пакет пен сақтандыруды бағалаймын.', 'I appreciate the social package and insurance.', 'security', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 48, 'Я не люблю рисковать финансами.', 'Мен қаржылай тәуекелге барғанды ұнатпаймын.', 'I don''t like to take financial risks.', 'security', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 49, 'Для меня важна предсказуемость будущего.', 'Мен үшін болашақтың болжамдылығы маңызды.', 'Predictability of the future is important to me.', 'security', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 50, 'Я планирую свои расходы заранее.', 'Мен шығындарымды алдын ала жоспарлаймын.', 'I plan my expenses in advance.', 'security', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 51, 'Я чувствую себя комфортно в стабильной среде.', 'Мен тұрақты ортада өзімді жайлы сезінемін.', 'I feel comfortable in a stable environment.', 'security', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 52, 'Я постоянно учусь новому.', 'Мен үнемі жаңа нәрселерді үйренемін.', 'I am constantly learning new things.', 'growth', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 53, 'Для меня важно профессиональное развитие.', 'Мен үшін кәсіби даму маңызды.', 'Professional development is important to me.', 'growth', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 54, 'Я ищу возможности для обучения.', 'Мен оқу мүмкіндіктерін іздеймін.', 'I am looking for learning opportunities.', 'growth', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 55, 'Я не люблю рутину, мне нужно разнообразие.', 'Маған рутина ұнамайды, маған әртүрлілік қажет.', 'I don''t like routine, I need variety.', 'growth', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 56, 'Я готов браться за сложные проекты ради опыта.', 'Мен тәжірибе үшін күрделі жобаларды қабылдауға дайынмын.', 'I am ready to take on complex projects for the sake of experience.', 'growth', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 57, 'Я хочу стать экспертом в своей области.', 'Мен өз саламда сарапшы болғым келеді.', 'I want to become an expert in my field.', 'growth', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 58, 'Меня вдохновляют новые знания.', 'Мені жаңа білім шабыттандырады.', 'New knowledge inspires me.', 'growth', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 59, 'Я инвестирую в свое образование.', 'Мен өз біліміме инвестиция саламын.', 'I invest in my education.', 'growth', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb),
(gen_random_uuid(), get_test_id('motivation'), 60, 'Для меня важно реализовывать свой потенциал.', 'Мен үшін өз әлеуетімді іске асыру маңызды.', 'It is important for me to realize my potential.', 'growth', false, '{"ru": ["Не важно", "Маловажно", "Средне", "Важно", "Очень важно"], "kk": ["Маңызды емес", "Аз маңызды", "Орташа", "Маңызды", "Өте маңызды"], "en": ["Not important", "Slightly important", "Neutral", "Important", "Very important"], "values": [0, 25, 50, 75, 100]}'::jsonb);
